---

- hosts: all
  remote_user: ansible

  tasks:
  - name: "Launch chkrootkit"
    shell: chkrootkit -q > /var/log/scan.log
    become: yes 
  - name: "Show scan result"
    shell: cat /var/log/scan.log
    become: yes 