---

- hosts: all
  remote_user: ansible

  tasks:
  - name: "Update Freshclam"
    shell: systemctl stop clamav-freshclam.service && freshclam && systemctl start clamav-freshclam.service 
    become: yes