---

- hosts: all
  remote_user: ansible

  tasks:
  - name: "Update all debian"
    apt:
      name: "*"
      state: latest
    become: yes
    when: ansible_facts['os_family'] == "Debian"




#  tasks:
#  - name: "Update all Centos"
#    command: sudo yum update && sudo yum upgrade -y
#    when: ansible_facts['os_family'] == "Centos"
    